INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (1, N'Alabama', N'AL')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (2, N'Alaska', N'AK')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (3, N'Arizona', N'AZ')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (4, N'Arkansas', N'AR')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (5, N'California', N'CA')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (6, N'Colorado', N'CO')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (7, N'Connecticut', N'CT')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (8, N'Delaware', N'DE')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (9, N'Florida', N'FL')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (10, N'Georgia', N'GA')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (11, N'Hawaii', N'HI')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (12, N'Idaho', N'ID')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (13, N'Illinois', N'IL')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (14, N'Indiana', N'IN')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (15, N'Iowa', N'IA')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (16, N'Kansas', N'KS')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (17, N'Kentucky', N'KY')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (18, N'Louisiana', N'LA')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (19, N'Maine', N'ME')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (20, N'Maryland', N'MD')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (21, N'Massachusetts', N'MA')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (22, N'Michigan', N'MI')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (23, N'Minnesota', N'MN')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (24, N'Mississippi', N'MS')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (25, N'Missouri', N'MO')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (26, N'Montana', N'MT')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (27, N'Nebraska', N'NE')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (28, N'Nevada', N'NV')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (29, N'New Hampshire', N'NH')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (30, N'New Jersey', N'NJ')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (31, N'New Mexico', N'NM')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (32, N'New York', N'NY')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (33, N'North Carolina', N'NC')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (34, N'North Dakota', N'ND')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (35, N'Ohio', N'OH')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (36, N'Oklahoma', N'OK')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (37, N'Oregon', N'OR')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (38, N'Pennsylvania', N'PA')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (39, N'Rhode Island', N'RI')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (40, N'South Carolina', N'SC')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (41, N'South Dakota', N'SD')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (42, N'Tennessee', N'TN')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (43, N'Texas', N'TX')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (44, N'Utah', N'UT')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (45, N'Vermont', N'VT')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (46, N'Virginia', N'VA')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (47, N'Washington', N'WA')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (48, N'West Virginia', N'WV')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (49, N'Wisconsin', N'WI')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (50, N'Wyoming', N'WY')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (51, N'Washington DC', N'DC')
INSERT [dbo].[AddressState] ([Id], [Name], [Abbreviation]) VALUES (52, N'Wyoming', N'WY')
INSERT [dbo].[AddressType] ([Id], [Value]) VALUES (0, N'Unknown')
INSERT [dbo].[AddressType] ([Id], [Value]) VALUES (1, N'Primary')
INSERT [dbo].[AddressType] ([Id], [Value]) VALUES (2, N'Mailing')
INSERT [dbo].[AddressType] ([Id], [Value]) VALUES (3, N'Other')
INSERT [dbo].[AddressType] ([Id], [Value]) VALUES (4, N'Billing')
INSERT [dbo].[ApplicantResidenceOwnershipType] ([Id], [Value]) VALUES (0, N'Unknown')
INSERT [dbo].[ApplicantResidenceOwnershipType] ([Id], [Value]) VALUES (1, N'Own')
INSERT [dbo].[ApplicantResidenceOwnershipType] ([Id], [Value]) VALUES (2, N'Rent')
INSERT [dbo].[ApplicantResidencePetDepositCoverageType] ([Id], [Value]) VALUES (0, N'Unknown')
INSERT [dbo].[ApplicantResidencePetDepositCoverageType] ([Id], [Value]) VALUES (1, N'per pet')
INSERT [dbo].[ApplicantResidencePetDepositCoverageType] ([Id], [Value]) VALUES (2, N'per household')
INSERT [dbo].[ApplicantResidenceType] ([Id], [Value]) VALUES (0, N'Unknown')
INSERT [dbo].[ApplicantResidenceType] ([Id], [Value]) VALUES (1, N'House')
INSERT [dbo].[ApplicantResidenceType] ([Id], [Value]) VALUES (2, N'Apartment')
INSERT [dbo].[ApplicantResidenceType] ([Id], [Value]) VALUES (3, N'Mobile Home')
INSERT [dbo].[ApplicantResidenceType] ([Id], [Value]) VALUES (4, N'Duplex')
INSERT [dbo].[ApplicantResidenceType] ([Id], [Value]) VALUES (5, N'Condo')
INSERT [dbo].[ApplicantStudentType] ([Id], [Value]) VALUES (0, N'N/A')
INSERT [dbo].[ApplicantStudentType] ([Id], [Value]) VALUES (1, N'Full Time')
INSERT [dbo].[ApplicantStudentType] ([Id], [Value]) VALUES (2, N'Part Time')
INSERT [dbo].[ApplicantType] ([Id], [Value]) VALUES (1, N'Adoption')
INSERT [dbo].[ApplicantType] ([Id], [Value]) VALUES (2, N'Foster')
INSERT [dbo].[EmailAddressType] ([Id], [Name]) VALUES (0, N'Unknown')
INSERT [dbo].[EmailAddressType] ([Id], [Name]) VALUES (1, N'Home')
INSERT [dbo].[EmailAddressType] ([Id], [Name]) VALUES (2, N'Work')
INSERT [dbo].[EmailAddressType] ([Id], [Name]) VALUES (3, N'School')
INSERT [dbo].[EmailAddressType] ([Id], [Name]) VALUES (4, N'Other')
INSERT [dbo].[FileType] ([Id], [Name]) VALUES (0, N'General')
INSERT [dbo].[FileType] ([Id], [Name]) VALUES (1, N'Home Page Slider Image')
INSERT [dbo].[FileType] ([Id], [Name]) VALUES (2, N'Golf Tournament Banner')
INSERT [dbo].[FileType] ([Id], [Name]) VALUES (3, N'RoughRiders Banner')
INSERT [dbo].[FileType] ([Id], [Name]) VALUES (4, N'Event Sponsor Logo')
INSERT [dbo].[FileType] ([Id], [Name]) VALUES (5, N'General Sponor Logo')
INSERT [dbo].[FileType] ([Id], [Name]) VALUES (6, N'Partner Logo')
INSERT [dbo].[PhoneNumberType] ([Id], [Value]) VALUES (0, N'Unknown')
INSERT [dbo].[PhoneNumberType] ([Id], [Value]) VALUES (1, N'Home')
INSERT [dbo].[PhoneNumberType] ([Id], [Value]) VALUES (2, N'Work')
INSERT [dbo].[PhoneNumberType] ([Id], [Value]) VALUES (3, N'Mobile')
INSERT [dbo].[PhoneNumberType] ([Id], [Value]) VALUES (4, N'Fax')
INSERT [dbo].[PhoneNumberType] ([Id], [Value]) VALUES (5, N'Other')
