CREATE TABLE [dbo].[Animal] (
    [Id]                        UNIQUEIDENTIFIER CONSTRAINT [DF_Animal_Id] DEFAULT (newid()) ROWGUIDCOL NOT NULL,
    [IsActive]                  BIT              NOT NULL,
    [IsAdoptionReady]           BIT              NOT NULL,
    [DateIntake]                DATETIME2 (0)    NULL,
    [AnimalIntakeTypeId]        INT              NULL,
    [DateAdopted]               DATETIME2 (0)    NULL,
    [Sex]                       NVARCHAR (1)     NOT NULL,
    [DateOfBirth]               DATETIME2 (0)    NULL,
    [RescueGroupId]             NVARCHAR (20)    NULL,
    [Name]                      NVARCHAR (200)   NOT NULL,
    [Alias]                     NVARCHAR (200)   NULL,
    [ShelterIntakeId]           NVARCHAR (50)    NULL,
    [RabiesId]                  NVARCHAR (50)    NULL,
    [MicrochipId]               NVARCHAR (50)    NULL,
    [MicrochipManufacturerId]   UNIQUEIDENTIFIER NULL,
    [IsMicrochipRegistered]     BIT              NOT NULL,
    [MicrochipRegistrationDate] DATETIME2 (0)    NULL,
    [PrimaryAnimalBreedId]      INT              NULL,
    [SecondaryAnimalBreedId]    INT              NULL,
    [IsMix]                     BIT              NOT NULL,
    [AnimalSizeId]              INT              NULL,
    [Weight]                    NVARCHAR (50)    NULL,
    [AnimalColorId]             INT              NULL,
    [IsHouseTrained]            BIT              NOT NULL,
    [IsNotKidFriendly]          BIT              NOT NULL,
    [IsNotCatFriendly]          BIT              NOT NULL,
    [IsNotDogFriendly]          BIT              NOT NULL,
    [IsSpecialNeeds]            BIT              NOT NULL,
    [HasBehaviorIssues]         BIT              NOT NULL,
    [IsDeceased]                BIT              NOT NULL,
    [DateDeceased]              DATETIME2 (0)    NULL,
    [AddedOnDate]               DATETIME2 (0)    NOT NULL,
    [AddedByUserId]             UNIQUEIDENTIFIER NOT NULL,
    [UpdatedOnDate]             DATETIME2 (0)    NULL,
    [UpdatedByUserId]           UNIQUEIDENTIFIER NULL,
    [SpecialNeedsNotes]         NVARCHAR (MAX)   NULL,
    [BehaviorIssueNotes]        NVARCHAR (MAX)   NULL,
    [PublicBiography]           NVARCHAR (MAX)   NULL,
    [InternalBiography]         NVARCHAR (MAX)   NULL,
    [Notes]                     NVARCHAR (MAX)   NULL,
    CONSTRAINT [PK_Animal] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_AnimalBreed_Id___Animal_PrimaryAnimalBreedId] FOREIGN KEY ([PrimaryAnimalBreedId]) REFERENCES [dbo].[AnimalBreed] ([Id]),
    CONSTRAINT [FK_AnimalBreed_Id___Animal_SecondaryAnimalBreedId] FOREIGN KEY ([SecondaryAnimalBreedId]) REFERENCES [dbo].[AnimalBreed] ([Id]),
    CONSTRAINT [FK_AnimalColor_Id___Animal_AnimalColorId] FOREIGN KEY ([AnimalColorId]) REFERENCES [dbo].[AnimalColor] ([Id]),
    CONSTRAINT [FK_AnimalIntakeType_Id___Animal_AnimalIntakeTypeId] FOREIGN KEY ([AnimalIntakeTypeId]) REFERENCES [dbo].[AnimalIntakeType] ([Id]),
    CONSTRAINT [FK_AnimalSize_Id___Animal_AnimalSizeId] FOREIGN KEY ([AnimalSizeId]) REFERENCES [dbo].[AnimalSize] ([Id])
);

