CREATE TABLE [dbo].[Applicant] (
    [Id]                                                  UNIQUEIDENTIFIER CONSTRAINT [DF_AdoptionApplications_Id] DEFAULT (newid()) ROWGUIDCOL NOT NULL,
    [PersonId]                                            UNIQUEIDENTIFIER NOT NULL,
    [ApplicantVeterinarianId]                             UNIQUEIDENTIFIER NULL,
    [ApplicantTypeId]                                     INT              NOT NULL,
    [DateSubmitted]                                       DATETIME2 (0)    NOT NULL,
    [AppNameFirst]                                        NVARCHAR (50)    NOT NULL,
    [AppNameLast]                                         NVARCHAR (50)    NOT NULL,
    [AppSpouseNameFirst]                                  NVARCHAR (50)    NULL,
    [AppSpouseNameLast]                                   NVARCHAR (50)    NULL,
    [AppCellPhone]                                        NVARCHAR (15)    NULL,
    [AppHomePhone]                                        NVARCHAR (15)    NULL,
    [AppAddressStreet1]                                   NVARCHAR (50)    NOT NULL,
    [AppAddressCity]                                      NVARCHAR (50)    NOT NULL,
    [AppAddressStateId]                                   INT              NULL,
    [AppAddressZIP]                                       NVARCHAR (10)    NOT NULL,
    [AppEmail]                                            NVARCHAR (200)   NULL,
    [AppDateBirth]                                        DATETIME2 (0)    NULL,
    [AppEmployer]                                         NVARCHAR (50)    NULL,
    [ResidenceOwnershipId]                                INT              NOT NULL,
    [ResidenceTypeId]                                     INT              NOT NULL,
    [ResidenceIsPetAllowed]                               BIT              NULL,
    [ResidenceIsPetDepositRequired]                       BIT              NULL,
    [ResidencePetDepositAmount]                           DECIMAL (18, 2)  NULL,
    [ResidenceIsPetDepositPaid]                           BIT              NULL,
    [ResidencePetDepositCoverageId]                       INT              NULL,
    [ResidencePetSizeWeightLimit]                         BIT              NULL,
    [ResidenceLandlordName]                               NVARCHAR (100)   NULL,
    [ResidenceLandlordNumber]                             NVARCHAR (14)    NULL,
    [ResidenceLengthOfResidence]                          NVARCHAR (30)    NOT NULL,
    [IsAppOrSpouseStudent]                                BIT              NOT NULL,
    [StudentTypeId]                                       INT              NULL,
    [IsAppTravelFrequent]                                 BIT              NOT NULL,
    [AppTravelFrequency]                                  NVARCHAR (50)    NULL,
    [WhatIfTravelPetPlacement]                            NVARCHAR (4000)  NULL,
    [WhatIfMovingPetPlacement]                            NVARCHAR (4000)  NULL,
    [ResidenceNumberOccupants]                            NVARCHAR (50)    NULL,
    [ResidenceAgesOfChildren]                             NVARCHAR (200)   NULL,
    [ResIdenceIsYardFenced]                               BIT              NOT NULL,
    [ResidenceFenceType]                                  NVARCHAR (50)    NULL,
    [ResidenceFenceHeight]                                NVARCHAR (50)    NULL,
    [LengthPetLeftAloneHoursInDay]                        NVARCHAR (20)    NULL,
    [LengthPetLeftAloneDaysOfWeek]                        NVARCHAR (20)    NULL,
    [PetKeptLocationInOutDoors]                           NVARCHAR (200)   NULL,
    [IsPetKeptLocationInOutDoorsTotallyInsIde]            BIT              NOT NULL,
    [IsPetKeptLocationInOutDoorsMostlyInsIde]             BIT              NOT NULL,
    [IsPetKeptLocationInOutDoorsTotallyOutsIde]           BIT              NOT NULL,
    [IsPetKeptLocationInOutDoorMostlyOutsIdes]            BIT              NOT NULL,
    [PetKeptLocationInOutDoorsExplain]                    NVARCHAR (4000)  NULL,
    [PetLeftAloneHours]                                   NVARCHAR (20)    NULL,
    [PetLeftAloneDays]                                    NVARCHAR (20)    NULL,
    [PetKeptLocationAloneRestriction]                     NVARCHAR (MAX)   NULL,
    [IsPetKeptLocationAloneRestrictionLooseIndoors]       BIT              NOT NULL,
    [IsPetKeptLocationAloneRestrictionGarage]             BIT              NOT NULL,
    [IsPetKeptLocationAloneRestrictionOutsIdeKennel]      BIT              NOT NULL,
    [IsPetKeptLocationAloneRestrictionCratedIndoors]      BIT              NOT NULL,
    [IsPetKeptLocationAloneRestrictionCratedOutdoors]     BIT              NOT NULL,
    [IsPetKeptLocationAloneRestrictionLooseInBackyard]    BIT              NOT NULL,
    [IsPetKeptLocationAloneRestrictionTiedUpOutdoors]     BIT              NOT NULL,
    [IsPetKeptLocationAloneRestrictionBasement]           BIT              NOT NULL,
    [IsPetKeptLocationAloneRestrictionOther]              BIT              NOT NULL,
    [PetKeptLocationAloneRestrictionExplain]              NVARCHAR (4000)  NULL,
    [PetKeptLocationSleepingRestriction]                  NVARCHAR (MAX)   NULL,
    [IsPetKeptLocationSleepingRestrictionLooseIndoors]    BIT              NOT NULL,
    [IsPetKeptLocationSleepingRestrictionGarage]          BIT              NOT NULL,
    [IsPetKeptLocationSleepingRestrictionOutsIdeKennel]   BIT              NOT NULL,
    [IsPetKeptLocationSleepingRestrictionCratedIndoors]   BIT              NOT NULL,
    [IsPetKeptLocationSleepingRestrictionCratedOutdoors]  BIT              NOT NULL,
    [IsPetKeptLocationSleepingRestrictionLooseInBackyard] BIT              NOT NULL,
    [IsPetKeptLocationSleepingRestrictionTiedUpOutdoors]  BIT              NOT NULL,
    [IsPetKeptLocationSleepingRestrictionBasement]        BIT              NOT NULL,
    [IsPetKeptLocationSleepingRestrictionInBedOwner]      BIT              NOT NULL,
    [IsPetKeptLocationSleepingRestrictionOther]           BIT              NOT NULL,
    [PetKeptLocationSleepingRestrictionExplain]           NVARCHAR (4000)  NULL,
    [PetAdoptionReason]                                   NVARCHAR (4000)  NULL,
    [IsPetAdoptionReasonHousePet]                         BIT              NOT NULL,
    [IsPetAdoptionReasonGuardDog]                         BIT              NOT NULL,
    [IsPetAdoptionReasonWatchDog]                         BIT              NOT NULL,
    [IsPetAdoptionReasonGift]                             BIT              NOT NULL,
    [IsPetAdoptionReasonCompanionChild]                   BIT              NOT NULL,
    [IsPetAdoptionReasonCompanionPet]                     BIT              NOT NULL,
    [IsPetAdoptionReasonJoggingPartner]                   BIT              NOT NULL,
    [IsPetAdoptionReasonOther]                            BIT              NOT NULL,
    [PetAdoptionReasonExplain]                            NVARCHAR (4000)  NULL,
    [FilterAppHasOwnedHuskyBefore]                        BIT              NOT NULL,
    [FilterAppTraitsDesired]                              NVARCHAR (4000)  NULL,
    [FilterAppIsCatOwner]                                 BIT              NOT NULL,
    [FilterAppCatsOwnedCount]                             NVARCHAR (20)    NULL,
    [FilterAppIsAwareHuskyAttributes]                     BIT              NOT NULL,
    [IsAllAdultsAgreedOnAdoption]                         BIT              NOT NULL,
    [IsAllAdultsAgreedOnAdoptionReason]                   NVARCHAR (4000)  NULL,
    [FilterAppDogsInterestedIn]                           NVARCHAR (4000)  NULL,
    [IsCompleted]                                         BIT              NULL,
    [IsDeleted]                                           BIT              NULL,
    [ApplicationFeeAmount] MONEY NULL, 
    [ApplicationFeePaymentMethod] NVARCHAR(50) NULL, 
    [ApplicationFeeTransactionId] NVARCHAR(36) NULL, 
    [Comments] NVARCHAR(MAX) NULL, 
    CONSTRAINT [PK_Applicant] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_AddressState_Id___Applicant_AppAddressStateId] FOREIGN KEY ([AppAddressStateId]) REFERENCES [dbo].[AddressState] ([Id]),
    CONSTRAINT [FK_ApplicantResidenceOwnershipType_Id___Applicant_ResidenceOwnershipId] FOREIGN KEY ([ResidenceOwnershipId]) REFERENCES [dbo].[ApplicantResidenceOwnershipType] ([Id]),
    CONSTRAINT [FK_ApplicantResidencePetDepositCoverageType_Id___Applicant_ResidencePetDepositCoverageId] FOREIGN KEY ([ResidencePetDepositCoverageId]) REFERENCES [dbo].[ApplicantResidencePetDepositCoverageType] ([Id]),
    CONSTRAINT [FK_ApplicantResidenceType_Id___Applicant_ResidenceTypeId] FOREIGN KEY ([ResidenceTypeId]) REFERENCES [dbo].[ApplicantResidenceType] ([Id]),
    CONSTRAINT [FK_ApplicantStudentType_Id___Applicant_StudentTypeId] FOREIGN KEY ([StudentTypeId]) REFERENCES [dbo].[ApplicantStudentType] ([Id]),
    CONSTRAINT [FK_ApplicantType_Id___Applicant_ApplicantTypeId] FOREIGN KEY ([ApplicantTypeId]) REFERENCES [dbo].[ApplicantType] ([Id]),
    CONSTRAINT [FK_ApplicantVeterinarian_Id___Applicant_ApplicantVeterinarianId] FOREIGN KEY ([ApplicantVeterinarianId]) REFERENCES [dbo].[ApplicantVeterinarian] ([Id])
);

