//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuskyRescue.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.People = new HashSet<Person>();
            this.Organizations = new HashSet<Organization>();
        }
    
        public System.Guid Id { get; set; }
        public int AddressTypeId { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public Nullable<int> AddressStateId { get; set; }
        public string ZipCode { get; set; }
        public string CountryId { get; set; }
        public bool IsBillingAddress { get; set; }
        public bool IsShippingAddress { get; set; }
    
        public virtual AddressState AddressState { get; set; }
        public virtual AddressType AddressType { get; set; }
        public virtual ICollection<Person> People { get; set; }
        public virtual ICollection<Organization> Organizations { get; set; }
    }
}
