//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuskyRescue.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalBreed
    {
        public AnimalBreed()
        {
            this.Animals = new HashSet<Animal>();
            this.Animals1 = new HashSet<Animal>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Animal> Animals { get; set; }
        public virtual ICollection<Animal> Animals1 { get; set; }
    }
}
