//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuskyRescue.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public Animal()
        {
            this.AnimalPlacements = new HashSet<AnimalPlacement>();
        }
    
        public System.Guid Id { get; set; }
        public bool IsActive { get; set; }
        public bool IsAdoptionReady { get; set; }
        public Nullable<System.DateTime> DateIntake { get; set; }
        public Nullable<int> AnimalIntakeTypeId { get; set; }
        public Nullable<System.DateTime> DateAdopted { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string RescueGroupId { get; set; }
        public string Name { get; set; }
        public string Alias { get; set; }
        public string ShelterIntakeId { get; set; }
        public string RabiesId { get; set; }
        public string MicrochipId { get; set; }
        public Nullable<System.Guid> MicrochipManufacturerId { get; set; }
        public bool IsMicrochipRegistered { get; set; }
        public Nullable<System.DateTime> MicrochipRegistrationDate { get; set; }
        public Nullable<int> PrimaryAnimalBreedId { get; set; }
        public Nullable<int> SecondaryAnimalBreedId { get; set; }
        public bool IsMix { get; set; }
        public Nullable<int> AnimalSizeId { get; set; }
        public string Weight { get; set; }
        public Nullable<int> AnimalColorId { get; set; }
        public bool IsHouseTrained { get; set; }
        public bool IsNotKidFriendly { get; set; }
        public bool IsNotCatFriendly { get; set; }
        public bool IsNotDogFriendly { get; set; }
        public bool IsSpecialNeeds { get; set; }
        public bool HasBehaviorIssues { get; set; }
        public bool IsDeceased { get; set; }
        public Nullable<System.DateTime> DateDeceased { get; set; }
        public System.DateTime AddedOnDate { get; set; }
        public System.Guid AddedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
        public Nullable<System.Guid> UpdatedByUserId { get; set; }
        public string SpecialNeedsNotes { get; set; }
        public string BehaviorIssueNotes { get; set; }
        public string PublicBiography { get; set; }
        public string InternalBiography { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<AnimalPlacement> AnimalPlacements { get; set; }
        public virtual AnimalBreed AnimalBreed { get; set; }
        public virtual AnimalBreed AnimalBreed1 { get; set; }
        public virtual AnimalColor AnimalColor { get; set; }
        public virtual AnimalIntakeType AnimalIntakeType { get; set; }
        public virtual AnimalSize AnimalSize { get; set; }
    }
}
