//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuskyRescue.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant
    {
        public Applicant()
        {
            this.ApplicantOwnedAnimals = new HashSet<ApplicantOwnedAnimal>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid PersonId { get; set; }
        public Nullable<System.Guid> ApplicantVeterinarianId { get; set; }
        public int ApplicantTypeId { get; set; }
        public System.DateTime DateSubmitted { get; set; }
        public string AppNameFirst { get; set; }
        public string AppNameLast { get; set; }
        public string AppSpouseNameFirst { get; set; }
        public string AppSpouseNameLast { get; set; }
        public string AppCellPhone { get; set; }
        public string AppHomePhone { get; set; }
        public string AppAddressStreet1 { get; set; }
        public string AppAddressCity { get; set; }
        public Nullable<int> AppAddressStateId { get; set; }
        public string AppAddressZIP { get; set; }
        public string AppEmail { get; set; }
        public Nullable<System.DateTime> AppDateBirth { get; set; }
        public string AppEmployer { get; set; }
        public int ResidenceOwnershipId { get; set; }
        public int ResidenceTypeId { get; set; }
        public Nullable<bool> ResidenceIsPetAllowed { get; set; }
        public Nullable<bool> ResidenceIsPetDepositRequired { get; set; }
        public Nullable<decimal> ResidencePetDepositAmount { get; set; }
        public Nullable<bool> ResidenceIsPetDepositPaid { get; set; }
        public Nullable<int> ResidencePetDepositCoverageId { get; set; }
        public Nullable<bool> ResidencePetSizeWeightLimit { get; set; }
        public string ResidenceLandlordName { get; set; }
        public string ResidenceLandlordNumber { get; set; }
        public string ResidenceLengthOfResidence { get; set; }
        public bool IsAppOrSpouseStudent { get; set; }
        public Nullable<int> StudentTypeId { get; set; }
        public bool IsAppTravelFrequent { get; set; }
        public string AppTravelFrequency { get; set; }
        public string WhatIfTravelPetPlacement { get; set; }
        public string WhatIfMovingPetPlacement { get; set; }
        public string ResidenceNumberOccupants { get; set; }
        public string ResidenceAgesOfChildren { get; set; }
        public bool ResIdenceIsYardFenced { get; set; }
        public string ResidenceFenceType { get; set; }
        public string ResidenceFenceHeight { get; set; }
        public string LengthPetLeftAloneHoursInDay { get; set; }
        public string LengthPetLeftAloneDaysOfWeek { get; set; }
        public string PetKeptLocationInOutDoors { get; set; }
        public bool IsPetKeptLocationInOutDoorsTotallyInsIde { get; set; }
        public bool IsPetKeptLocationInOutDoorsMostlyInsIde { get; set; }
        public bool IsPetKeptLocationInOutDoorsTotallyOutsIde { get; set; }
        public bool IsPetKeptLocationInOutDoorMostlyOutsIdes { get; set; }
        public string PetKeptLocationInOutDoorsExplain { get; set; }
        public string PetLeftAloneHours { get; set; }
        public string PetLeftAloneDays { get; set; }
        public string PetKeptLocationAloneRestriction { get; set; }
        public bool IsPetKeptLocationAloneRestrictionLooseIndoors { get; set; }
        public bool IsPetKeptLocationAloneRestrictionGarage { get; set; }
        public bool IsPetKeptLocationAloneRestrictionOutsIdeKennel { get; set; }
        public bool IsPetKeptLocationAloneRestrictionCratedIndoors { get; set; }
        public bool IsPetKeptLocationAloneRestrictionCratedOutdoors { get; set; }
        public bool IsPetKeptLocationAloneRestrictionLooseInBackyard { get; set; }
        public bool IsPetKeptLocationAloneRestrictionTiedUpOutdoors { get; set; }
        public bool IsPetKeptLocationAloneRestrictionBasement { get; set; }
        public bool IsPetKeptLocationAloneRestrictionOther { get; set; }
        public string PetKeptLocationAloneRestrictionExplain { get; set; }
        public string PetKeptLocationSleepingRestriction { get; set; }
        public bool IsPetKeptLocationSleepingRestrictionLooseIndoors { get; set; }
        public bool IsPetKeptLocationSleepingRestrictionGarage { get; set; }
        public bool IsPetKeptLocationSleepingRestrictionOutsIdeKennel { get; set; }
        public bool IsPetKeptLocationSleepingRestrictionCratedIndoors { get; set; }
        public bool IsPetKeptLocationSleepingRestrictionCratedOutdoors { get; set; }
        public bool IsPetKeptLocationSleepingRestrictionLooseInBackyard { get; set; }
        public bool IsPetKeptLocationSleepingRestrictionTiedUpOutdoors { get; set; }
        public bool IsPetKeptLocationSleepingRestrictionBasement { get; set; }
        public bool IsPetKeptLocationSleepingRestrictionInBedOwner { get; set; }
        public bool IsPetKeptLocationSleepingRestrictionOther { get; set; }
        public string PetKeptLocationSleepingRestrictionExplain { get; set; }
        public string PetAdoptionReason { get; set; }
        public bool IsPetAdoptionReasonHousePet { get; set; }
        public bool IsPetAdoptionReasonGuardDog { get; set; }
        public bool IsPetAdoptionReasonWatchDog { get; set; }
        public bool IsPetAdoptionReasonGift { get; set; }
        public bool IsPetAdoptionReasonCompanionChild { get; set; }
        public bool IsPetAdoptionReasonCompanionPet { get; set; }
        public bool IsPetAdoptionReasonJoggingPartner { get; set; }
        public bool IsPetAdoptionReasonOther { get; set; }
        public string PetAdoptionReasonExplain { get; set; }
        public bool FilterAppHasOwnedHuskyBefore { get; set; }
        public string FilterAppTraitsDesired { get; set; }
        public bool FilterAppIsCatOwner { get; set; }
        public string FilterAppCatsOwnedCount { get; set; }
        public bool FilterAppIsAwareHuskyAttributes { get; set; }
        public bool IsAllAdultsAgreedOnAdoption { get; set; }
        public string IsAllAdultsAgreedOnAdoptionReason { get; set; }
        public string FilterAppDogsInterestedIn { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<decimal> ApplicationFeeAmount { get; set; }
        public string ApplicationFeePaymentMethod { get; set; }
        public string ApplicationFeeTransactionId { get; set; }
        public string Comments { get; set; }
    
        public virtual AddressState AddressState { get; set; }
        public virtual ICollection<ApplicantOwnedAnimal> ApplicantOwnedAnimals { get; set; }
        public virtual ApplicantResidenceOwnershipType ApplicantResidenceOwnershipType { get; set; }
        public virtual ApplicantResidencePetDepositCoverageType ApplicantResidencePetDepositCoverageType { get; set; }
        public virtual ApplicantResidenceType ApplicantResidenceType { get; set; }
        public virtual ApplicantStudentType ApplicantStudentType { get; set; }
        public virtual ApplicantType ApplicantType { get; set; }
        public virtual ApplicantVeterinarian ApplicantVeterinarian { get; set; }
    }
}
