//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuskyRescue.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetResource
    {
        public AspNetResource()
        {
            this.AspNetRoleResources = new HashSet<AspNetRoleResource>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public int Operations { get; set; }
    
        public virtual ICollection<AspNetRoleResource> AspNetRoleResources { get; set; }
    }
}
