//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuskyRescue.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailAddress
    {
        public EmailAddress()
        {
            this.People = new HashSet<Person>();
            this.Organizations = new HashSet<Organization>();
        }
    
        public System.Guid Id { get; set; }
        public int EmailAddressTypeId { get; set; }
        public string Address { get; set; }
    
        public virtual EmailAddressType EmailAddressType { get; set; }
        public virtual ICollection<Person> People { get; set; }
        public virtual ICollection<Organization> Organizations { get; set; }
    }
}
