//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuskyRescue.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventRegistration
    {
        public EventRegistration()
        {
            this.EventRegistrationPersons = new HashSet<EventRegistrationPerson>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid EventId { get; set; }
        public System.DateTime DateSubmitted { get; set; }
        public bool HasPaid { get; set; }
        public Nullable<System.Guid> PaymentEventRegistrationId { get; set; }
        public int NumberTicketsBought { get; set; }
        public decimal AmountPaid { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
        public Nullable<System.Guid> UpdatedByUserId { get; set; }
        public string RegistrationComments { get; set; }
        public string Notes { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual ICollection<EventRegistrationPerson> EventRegistrationPersons { get; set; }
        public virtual PaymentEventRegistration PaymentEventRegistration { get; set; }
    }
}
