//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuskyRescue.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventDonation
    {
        public System.Guid Id { get; set; }
        public System.Guid EventId { get; set; }
        public System.Guid PaymentDonationId { get; set; }
        public bool HaveReceivedDonation { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual PaymentDonation PaymentDonation { get; set; }
    }
}
