//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuskyRescue.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.EventDonations = new HashSet<EventDonation>();
            this.EventRegistrations = new HashSet<EventRegistration>();
            this.EventSponsorships = new HashSet<EventSponsorship>();
            this.EventSponsors = new HashSet<EventSponsor>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid OrganizationId { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOnDate { get; set; }
        public System.DateTime AddedOnDate { get; set; }
        public string AddedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
        public string UpdatedByUserId { get; set; }
        public string Name { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public bool IsAllDayEvent { get; set; }
        public bool IsRoughRidersEvent { get; set; }
        public bool IsGolfTournamentEvent { get; set; }
        public bool IsRaffleEvent { get; set; }
        public bool IsMeetAndGreetEvent { get; set; }
        public bool IsDogWashEvent { get; set; }
        public bool Is5kEvent { get; set; }
        public bool IsOtherEvent { get; set; }
        public string OtherEventDescription { get; set; }
        public bool AreTicketsSold { get; set; }
        public decimal TicketPrice { get; set; }
        public Nullable<decimal> TicketPriceOther { get; set; }
        public string PublicDescription { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<EventDonation> EventDonations { get; set; }
        public virtual ICollection<EventRegistration> EventRegistrations { get; set; }
        public virtual ICollection<EventSponsorship> EventSponsorships { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<EventSponsor> EventSponsors { get; set; }
    }
}
