//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuskyRescue.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventSponsorship
    {
        public EventSponsorship()
        {
            this.EventSponsors = new HashSet<EventSponsor>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid EventId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string Name { get; set; }
        public decimal Cost { get; set; }
        public int NumberOfAllowedSponsors { get; set; }
        public int NumberOfSponsors { get; set; }
        public System.DateTime AddedOnDate { get; set; }
        public string AddedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
        public string UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> DeletedOnDate { get; set; }
        public string PublicDescription { get; set; }
        public string Notes { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual ICollection<EventSponsor> EventSponsors { get; set; }
    }
}
