//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuskyRescue.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventSponsor
    {
        public EventSponsor()
        {
            this.Files = new HashSet<File>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid EventId { get; set; }
        public Nullable<System.Guid> OrganizationId { get; set; }
        public Nullable<System.Guid> PersonId { get; set; }
        public System.Guid EventSponsorshipId { get; set; }
        public bool HaveReceivedSingage { get; set; }
        public bool HaveReceviedLogo { get; set; }
        public bool HasSponsorMoneyBeenReceived { get; set; }
        public decimal AmountPaid { get; set; }
        public System.DateTime AddedOnDate { get; set; }
        public string AddedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
        public string UpdatedByUserId { get; set; }
        public string Notes { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual EventSponsorship EventSponsorship { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<File> Files { get; set; }
    }
}
