//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuskyRescue.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public File()
        {
            this.EventSponsors = new HashSet<EventSponsor>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public int FileTypeId { get; set; }
        public string ContentType { get; set; }
        public byte[] Content { get; set; }
    
        public virtual FileType FileType { get; set; }
        public virtual ICollection<EventSponsor> EventSponsors { get; set; }
    }
}
