//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuskyRescue.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HuskyRescueEntities : DbContext
    {
        public HuskyRescueEntities()
            : base("name=HuskyRescueEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<AddressState> AddressStates { get; set; }
        public virtual DbSet<AddressType> AddressTypes { get; set; }
        public virtual DbSet<Animal> Animals { get; set; }
        public virtual DbSet<AnimalBreed> AnimalBreeds { get; set; }
        public virtual DbSet<AnimalColor> AnimalColors { get; set; }
        public virtual DbSet<AnimalIntakeType> AnimalIntakeTypes { get; set; }
        public virtual DbSet<AnimalPlacement> AnimalPlacements { get; set; }
        public virtual DbSet<AnimalPlacementType> AnimalPlacementTypes { get; set; }
        public virtual DbSet<AnimalSize> AnimalSizes { get; set; }
        public virtual DbSet<Applicant> Applicants { get; set; }
        public virtual DbSet<ApplicantOwnedAnimal> ApplicantOwnedAnimals { get; set; }
        public virtual DbSet<ApplicantResidenceOwnershipType> ApplicantResidenceOwnershipTypes { get; set; }
        public virtual DbSet<ApplicantResidencePetDepositCoverageType> ApplicantResidencePetDepositCoverageTypes { get; set; }
        public virtual DbSet<ApplicantResidenceType> ApplicantResidenceTypes { get; set; }
        public virtual DbSet<ApplicantStudentType> ApplicantStudentTypes { get; set; }
        public virtual DbSet<ApplicantType> ApplicantTypes { get; set; }
        public virtual DbSet<ApplicantVeterinarian> ApplicantVeterinarians { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<EmailAddress> EmailAddresses { get; set; }
        public virtual DbSet<EmailAddressType> EmailAddressTypes { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<InventoryCategory> InventoryCategories { get; set; }
        public virtual DbSet<InventoryImage> InventoryImages { get; set; }
        public virtual DbSet<InventoryPlacement> InventoryPlacements { get; set; }
        public virtual DbSet<MarketingPreference> MarketingPreferences { get; set; }
        public virtual DbSet<MicrochipManufacturer> MicrochipManufacturers { get; set; }
        public virtual DbSet<OrganizationContact> OrganizationContacts { get; set; }
        public virtual DbSet<PaymentDonation> PaymentDonations { get; set; }
        public virtual DbSet<PaymentEventRegistration> PaymentEventRegistrations { get; set; }
        public virtual DbSet<PaymentStore> PaymentStores { get; set; }
        public virtual DbSet<StoreCart> StoreCarts { get; set; }
        public virtual DbSet<StoreCartItem> StoreCartItems { get; set; }
        public virtual DbSet<StoreOrder> StoreOrders { get; set; }
        public virtual DbSet<StoreOrderDetail> StoreOrderDetails { get; set; }
        public virtual DbSet<StoreShippingMethod> StoreShippingMethods { get; set; }
        public virtual DbSet<SystemAuditLogEntityType> SystemAuditLogEntityTypes { get; set; }
        public virtual DbSet<SystemErrorLog> SystemErrorLogs { get; set; }
        public virtual DbSet<Website> Websites { get; set; }
        public virtual DbSet<SystemAuditLog> SystemAuditLogs { get; set; }
        public virtual DbSet<AspNetResource> AspNetResources { get; set; }
        public virtual DbSet<AspNetRoleResource> AspNetRoleResources { get; set; }
        public virtual DbSet<PhoneNumberType> PhoneNumberTypes { get; set; }
        public virtual DbSet<PhoneNumber> PhoneNumbers { get; set; }
        public virtual DbSet<SystemSetting> SystemSettings { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventDonation> EventDonations { get; set; }
        public virtual DbSet<EventRegistration> EventRegistrations { get; set; }
        public virtual DbSet<EventRegistrationPerson> EventRegistrationPersons { get; set; }
        public virtual DbSet<EventSponsorship> EventSponsorships { get; set; }
        public virtual DbSet<EventSponsorshipItem> EventSponsorshipItems { get; set; }
        public virtual DbSet<EventSponsorshipLevel> EventSponsorshipLevels { get; set; }
        public virtual DbSet<EventSponsor> EventSponsors { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<FileType> FileTypes { get; set; }
    }
}
