//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuskyRescue.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryPlacement
    {
        public System.Guid Id { get; set; }
        public System.Guid InventoryId { get; set; }
        public int QuantityAtLocation { get; set; }
        public System.DateTime AddedOnDate { get; set; }
        public System.Guid AddedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
        public Nullable<System.Guid> UpdatedByUserId { get; set; }
        public Nullable<System.Guid> PersonId { get; set; }
        public Nullable<System.Guid> OrganizationId { get; set; }
        public string Notes { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual Person Person { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
