//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuskyRescue.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryImage
    {
        public System.Guid Id { get; set; }
        public System.Guid InventoryId { get; set; }
        public string RelativePath { get; set; }
        public string PhysicalPath { get; set; }
        public string AltText { get; set; }
    
        public virtual Inventory Inventory { get; set; }
    }
}
