//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuskyRescue.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public Inventory()
        {
            this.InventoryImages = new HashSet<InventoryImage>();
            this.InventoryPlacements = new HashSet<InventoryPlacement>();
            this.StoreCartItems = new HashSet<StoreCartItem>();
            this.StoreOrderDetails = new HashSet<StoreOrderDetail>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid InventoryCategoryId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }
        public decimal CostToBuy { get; set; }
        public bool IsAvailableInStore { get; set; }
        public decimal StoreSellPrice { get; set; }
        public decimal ShippingCost { get; set; }
        public System.DateTime AddedOnDate { get; set; }
        public System.Guid AddedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
        public Nullable<System.Guid> UpdatedByUserId { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<InventoryImage> InventoryImages { get; set; }
        public virtual ICollection<InventoryPlacement> InventoryPlacements { get; set; }
        public virtual ICollection<StoreCartItem> StoreCartItems { get; set; }
        public virtual ICollection<StoreOrderDetail> StoreOrderDetails { get; set; }
        public virtual InventoryCategory InventoryCategory { get; set; }
    }
}
