//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuskyRescue.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public Organization()
        {
            this.AnimalPlacements = new HashSet<AnimalPlacement>();
            this.InventoryPlacements = new HashSet<InventoryPlacement>();
            this.MicrochipManufacturers = new HashSet<MicrochipManufacturer>();
            this.OrganizationContacts = new HashSet<OrganizationContact>();
            this.Addresses = new HashSet<Address>();
            this.EmailAddresses = new HashSet<EmailAddress>();
            this.MarketingPreferences = new HashSet<MarketingPreference>();
            this.PhoneNumbers = new HashSet<PhoneNumber>();
            this.Websites = new HashSet<Website>();
            this.Events = new HashSet<Event>();
            this.EventSponsors = new HashSet<EventSponsor>();
        }
    
        public System.Guid Id { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public bool IsBoardingPlace { get; set; }
        public bool IsAnimalClinic { get; set; }
        public bool IsDonor { get; set; }
        public bool IsGrantGiver { get; set; }
        public System.DateTime AddedOnDate { get; set; }
        public string AddedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedOnDate { get; set; }
        public string UpdatedByUserId { get; set; }
        public System.DateTime DateActive { get; set; }
        public Nullable<System.DateTime> DateInactive { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public string Name { get; set; }
        public string EIN { get; set; }
        public string Notes { get; set; }
        public bool IsSponsor { get; set; }
    
        public virtual ICollection<AnimalPlacement> AnimalPlacements { get; set; }
        public virtual ICollection<InventoryPlacement> InventoryPlacements { get; set; }
        public virtual ICollection<MicrochipManufacturer> MicrochipManufacturers { get; set; }
        public virtual ICollection<OrganizationContact> OrganizationContacts { get; set; }
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<EmailAddress> EmailAddresses { get; set; }
        public virtual ICollection<MarketingPreference> MarketingPreferences { get; set; }
        public virtual ICollection<PhoneNumber> PhoneNumbers { get; set; }
        public virtual ICollection<Website> Websites { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<EventSponsor> EventSponsors { get; set; }
    }
}
