//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuskyRescue.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDonation
    {
        public PaymentDonation()
        {
            this.EventDonations = new HashSet<EventDonation>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> PaymentId { get; set; }
        public bool HasThankYouCardBeenSent { get; set; }
        public bool IsDonatedItem { get; set; }
        public Nullable<decimal> DonatedItemCashValue { get; set; }
        public string DonatedItemDescription { get; set; }
    
        public virtual Payment Payment { get; set; }
        public virtual ICollection<EventDonation> EventDonations { get; set; }
    }
}
